version: 2.1

orbs:
  slack: circleci/slack@4.9.3

executors:
  linux-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/workspace

jobs:
  build:
    executor: linux-executor
    steps:
      - checkout
      - run:
          name: Show current system date
          command: date

  test:
    executor: linux-executor
    steps:
      - run:
          name: Check Python version
          command: python --version  # Corrected command here

  notify:
    docker:
      - image: cimg/python:3.9  # You can use the same executor image, or use the slack orb's image
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - test
      - notify:
          context: slack-secrets  # Ensure the Slack context is defined
