version: 2.1

orbs:
  slack: circleci/slack@4.9.3

executors:
  linux-executor:
    docker:
      - image: cimg/python:3.9  # Use a Docker image with Python (you can choose any image you prefer)
    working_directory: ~/workspace  # Set the working directory for your project

jobs:
  build:
    executor: linux-executor
    steps:
      # Checkout the code from your repository
      - checkout
      
      # Update the system and install sample packages
      - run:
          name: Update system and install curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl

      # Run a simple Linux command (for example, print the system date)
      - run:
          name: Show current system date
          command: date

      # Install any additional dependencies (if necessary)
      - run:
          name: Install sample dependencies
          command: |
            sudo apt-get install -y git
            git --version

      # Run a simple shell command (echo a message)
      - run:
          name: Echo a message
          command: echo "Hello from CircleCI!"

  test:
    executor: linux-executor
    steps:
      # Run some basic test or command (example: test Python version)
      - run:
          name: Check Python version
          command: python --version

  # Job to notify on success or failure
  slack_notification:
    docker:
      - image: cimg/python:3.9
    steps:
      # Notify Slack on success or failure
      - slack/notify:
          event: always  # This will notify on both success and failure
          template: basic_fail_1  # Template for failure (can use basic_success_1 for success)
          context: slack-secrets  # Make sure this context contains SLACK_ACCESS_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - slack_notification:
          requires:
            - build
            - test

