version: 2.1

jobs:
  job1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Create Hello.txt file
          command: |
            ls -lart
            pwd
            checksum=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      - save_cache:
          paths:
            - ./1 # specify the full file path here (relative to the workspace)
          key: java--{{ $checksum "1" }}  # Cache key based on the file

  job2:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: java--{{ 512 "1" }}  # Restore the cache with the same key used in job1
      - run:
          name: checking for the contents in file 1
          command: |
            ls -lart
            pwd
            cd 
            

workflows:
  version: 2
  workflow:
    jobs:
      - job1
      - job2:
          requires:
            - job1
