version: 2.1

orbs:
  slack: circleci/slack@4.1.1

contexts:
  - slack-secrets

jobs:
  build:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Build
          command: |
            echo "Building..."
            exit 1

    post-steps:
      - slack/notify:
          context: slack
          custom: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ *Failure* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}`"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: fail

  deploy:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Deploy
          command: |
            echo "Deploying..."
            exit 0

    post-steps:
      - slack/notify:
          context: slack-secrets
          custom: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *Success* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}`"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
