version: 2.1
orbs:
  slack: circleci/slack@5.1.1
jobs:

  job1:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            echo "hi"
  job2:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            echo "hi"
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Pipeline Completed*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
  workflows:
  your-workflow:
    jobs:
      - job1
      - job2
      - notify:
          requires:
            - job1
            - job2
          context: slack-secrets
