version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Use a Docker image that fits your environmentsss
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: List files in the current directoryy





          
          command: ls -lar
workflows:
  version: 2
  deploy_staging_and_prod:
    jobs:
      - build
