

version: 2.1

# Define the jobs
jobs:
  test:
    docker:
      - image: cimg/python:3.8  # Use a Docker image with Python pre-installed
    steps:
      - checkout  # Check out the code from the repo
      - when:
          condition:
            equal: [circel-ci-projectsetup, << pipeline.gitbrach >>]
          steps:
            - run:
                name: testing when condition
                command: echo "hello testing when condition sucessfully deployed"
      # - run:
      #     name: Install dependencies
      #     command: |
      #         echo "hi"
      # - run:
      #     name: Run tests
      #     command: |
      #         echo "Hello"

  deploy:
    docker:
      - image: cimg/python:3.8  # Use the same Docker image for consistency
    steps:
      - checkout  # Check out the code from the repo
      - run:
          name: Deploy the app
          command: |
            echo "Deploying the application..."
            # Example: deploy command (replace with your actual deployment logic)
            # curl -X POST -d "app=myapp" https://example.com/deploy

# Define the workflows
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test        # Run the test job first
      - deploy:
          requires:
            - test   # Run deploy job only after test job succeeds
          filters:
            branches:
              only:
                - master  # Deploy job only runs on the master branch
