version: 2.1

jobs:
 
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      - run: |
          touch ./java-web-app-docker-master/TESTING
          echo "from cache to test Anudeep" >> ./java-web-app-docker-master/HELLO.txt
          cat ./java-web-app-docker-master/HELLO.txt
          echo "from cache to test Anudeep Dachepalli" >> ./java-web-app-docker-master/HELLO.txt
          echo "from cache to test 2 caches" >> ./test-code/how.txt
          echo $(find ./java-web-app-docker-master -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  > CACHE_KEY20
          echo $(find ./test-code -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  > TESTCODE
          cat CACHE_KEY20
          cat TESTCODE

      - run: cat CACHE_KEY20
      - save_cache:
          key: tested-cache-v1-{{ checksum "CACHE_KEY20" }}___{{ checksum "TESTCODE" }}
          paths:
            - java-web-app-docker-master
            - test-code
      - restore_cache:
          key: tested-cache-v1-{{ checksum "CACHE_KEY20" }}
      - run:
          name: verifying_cache
          command: |
            ls ./java-web-app-docker-master/
            cat ./java-web-app-docker-master/hello.txt
            ls 
            ls | grep CACHE
            ls ./test-code/
      - persist_to_workspace:
          root: ./
          paths:
            - ./CACHE_KEY20
            - ./TESTCODE

  volumes:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: adding new files to volumetest
          command: |
             echo "volume" > volumetesting
             echo "volume2" > volume2
             ls 
             pwd
      - persist_to_workspace:
          root: ./
          paths:
            - ./volumetesting
            - ./volume2
      
  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: tested-cache-v1-{{ checksum "CACHE_KEY20" }}___{{ checksum "TESTCODE" }}
      - run: 
          name: checking_cache
          command: |
            ls -lart
            cat ./java-web-app-docker-master/hello.txt
            ls ./java-web-app-docker-master 
            cat ./test-code/how.txt
            ls -lart /tmp



workflows:
  version: 2
  workflow:
    jobs:
      # - job1
      # - job2:
      #     requires:
      #       - job1
      - build
      - deploy:
          requires:
            - build
            - volumes
      - volumes
            
