version: 2.1

jobs:
  say_hello:
    docker:
      - image: cimg/base:stable  # Use a basic CircleCI Docker images
    steps:
      - run:
          name: Print Echo Statement
          command: echo "Hello from CircleC!"

workflows:
  version: 2
  simple_workflow:
    jobs:
      - say_hello
