version: 2.1
 
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Example base image
    working_directory: /workspace
 
jobs:
  example-job:
    executor: docker-executor
    parameters:
      command_name:
        type: string
        default: "pwd"  # Default to 'pwd' if no command is passed
    steps:
      - checkout  # Checkout the repository
      - run:
          name: Run the dynamic command
          command: << parameters.command_name >>  # This will run the command passed in the parameter
 
workflows:
  version: 2
  build:
    jobs:
      - example-job:
          command_name: "pwd"  # You can dynamically specify the command here (e.g., 'pwd', 'ls', etc.)

has context menu
