version: 2.1

jobs:
  job1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Create Hello.txt file
          command:  |
            echo "Hello World, Hi How are you " >> 1
            ls -lart
            pwd
      - save_cache:
          paths:
            - 1
          key: hello--{{ checksum "1" }}

 
workflows:
  version: 2
  workflow:
    jobs:
      - job1
      # - job2:
      #     requires:
      #       - job1
