version: 2.1

jobs:
  job1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Create Hello.txt file
          command:  |
            echo "Hello World" > Hello.txt
            ls -lart
      - save_cache:
          paths:
            - Hello.txt
          key: cache--{{ checksum "Hello.txt" }}

  job2:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: cache--{{ checksum "Hello.txt" }}
      - run:
          name: Print Hello.txt content
          command: ls -lart

workflows:
  version: 2
  workflow:
    jobs:
      - job1
      - job2:
          requires:
            - job1
