version: 2.1

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/status:
        fail_only: true
  context: slack-secrets

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            echo "hi"
  last-job:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            echo "hello"
  
workflows:
  version: 2
  workflow:
    jobs:
      - build: *slack-fail-post-step
      - last-job:
          requires:
            - build
          post-steps:
            - slack/status
          context: slack-secrets
