version: 2.1

orbs:
  slack: circleci/slack@4.9.3

executors:
  linux-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/workspace

jobs:
  build:
    executor: linux-executor
    steps:
      - checkout
      - run:
          name: Update system and install curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl


  test:
    executor: linux-executor
    steps:
      - run:
          name: Check Python version
          command: python -version

  slack_notification:
    docker:
      - image: cimg/base:current
    steps:
      - slack/notify:
          event: always
          template: success_tagged_deploy_1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - slack_notification:
          requires:
            - build
            - test
          context: slack-secrets




