version: 2.1

# Define Orbs
orbs:
  slack: circleci/slack@4.4.1  # Slack Orb version

# Jobs
jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Choose your base image
    steps:
      - checkout  # Checkout the code
      - run:
          name: Run Tests
          command: |
            # Replace with your test command
            pytest tests/  # Example command for running tests
          
  # Notify Slack on success or failure
  notify:
    docker:
      - image: circleci/python:3.9
    steps:
      - slack/notify:
          channel: "#your-slack-channel"
          event: "fail"  # Notify on failure
          text: "The build has failed, but we're working on it! 😅"
          color: "danger"  # Red color for failure
          
      - slack/notify:
          channel: "#your-slack-channel"
          event: "success"  # Always notify on success (even if the build fails)
          text: "Build pipeline has completed! Even though it failed, we're making progress 💪"
          color: "good"  # Green color for success

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify:
          requires:
            - build  # Wait for the build job to finish
          filters:
            success:
              - true  # Notify for success
            failure:
              - true  # Notify for failure
        context: slack-secrets

