
version: 2.1
executors:
  ll_public_executor:
    docker:
      - image: ubuntu:20.04
commands:
  build_ll_public:
    description: 'Builds a CRA and caches the build'
    parameters:
      command:
        type: string
    steps:

      - run:
          name: Verify and Install Dependencies
          command: |
            if [ 5==5 ]; then
               echo "Cache restored, skipping yarn install."
            else
               echo "Cache not found, running yarn install."
               echo "hi"
            fi
      - run:  mkdir test && cd test && touch 1 && ls -lart && pwd

     
      - run:   << parameters.command >>
      - when:
          condition:
            or:
              - equal: [circelci-project-setup , << pipeline.git.branch >>]
              - equal: [qa, << pipeline.git.branch >>]
              - matches: { pattern: '^sb-\S+$', value: << pipeline.git.branch >> }
              - matches: { pattern: '^hotfix\/\S+$', value: << pipeline.git.branch >> }
          steps:
            
            - save_cache:
                key: test
                paths:
                  - test/1

jobs:
  build_internal_dashboard:
    executor: ll_public_executor
    steps:
      - checkout
      - build_ll_public:
          command: echo "hello world"
  cachess:
    executor: ll_public_executor
    steps:
      - checkout
      - restore_cache:
          key: test
      - run: ls -lart && pwd

workflows:
  version: 2
  test-and-build:
    jobs:
      -  build_internal_dashboard
      -  cachess
  
