version: 2.1

orbs:
  slack: circleci/slack@4.9.3

executors:
  linux-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/workspace


jobs:
  deploy:
    executor:
      name: linux-executor
    steps:
      - checkout
      - run:
          command:  python -version
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context: slack-secrets
