version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Use a Docker image that fits your environment
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: List files in the current directory
          command: ls -lar
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            echo "Running tests..."
            # Example test command
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
