version: 2.1

commands:
  test:
    description: "A simple test command"
    steps:
      - when:
          condition:
            or:
              - equal: [circleci-project-setup, << pipeline.git.branch >>]
          steps:
            - run:
                name: "Test"
                command: echo "yess"

jobs:
  hello-command:
    description: "Job to execute the test command"
    steps:
      - test  # This references the command defined above

workflows:
  version: 2
  example-workflow:
    jobs:
      - hello-command
