version: 2.1

jobs:
  job1:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Run job 1
          command: |
            echo "Running job 1"
            exit 1  # Simulate failure

  job2:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Run job 2
          command: |
            echo "Running job 2"
            exit 0  # Simulate success

  job3:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Run job 3
          command: |
            echo "Running job 3"
            exit 0  # Simulate success

  final_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Always run this job
          command: echo "This job runs no matter what!"

workflows:
  version: 2
  build:
    jobs:
      - job1
      - job2
      - job3
      - final_job:
          requires:
            - job1
            - job2
            - job3
          filters:
            branches:
              only: master
          finish: true  # Ensure this job runs after all other jobs
