version: 2.1

orbs:
  slack: circleci/slack@4.9.3

executors:
  linux-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/workspace

jobs:
  build:
    executor: linux-executor
    steps:
      - checkout
      - run:
          name: Update system and install curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
      - run:
          name: Show current system date
          command: date
      - run:
          name: Install sample dependencies
          command: |
            sudo apt-get install -y git
            git --version
      - run:
          name: Echo a message
          command: echo "Hello from CircleCI!"

  test:
    executor: linux-executor
    steps:
      - run:
          name: Check Python version
          command: python --version

  slack_notification:
    docker:
      - image: cimg/base:current
    steps:
      - slack/notify:
          event: always  # This will ensure the Slack notification is always sent
          template: basic_fail_1

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - test
      - slack_notification:
          requires:
            - build
            - test
          context: slack-secrets
