version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Use a Docker image that fits your environment
    steps:
      - checkout  #Check out the code from the repositoryy
      - run:
          name: List files in the current directory
          command: ls -la
workflows:
  version: 2
  deploy_staging_and_prod:
    jobs:
      - build
