version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Building..."

  test:
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Testing..."

  waiter:
    docker:
      - image: circleci/node:14
    steps:
      - run: |
          if [ "$(circleci pipeline status)" != "success" ]; then
            echo "{\"extra-job\": true}" > params.json
          fi

workflows:
  main:
    jobs:
      - build
      - test
      - waiter:
          requires:
            - build
            - test

  continuation:
    jobs:
      - slack-notification:
          context: slack-secretes
          when: << pipeline.parameters.extra-job >>
    parameters:
      extra-job:
        type: boolean
        default: false
