version: 2.1
# commands:
#   test:
#     parameters:
#       command:
#         type: string
#     steps:
#       - run:
#           name: test
#           command: |
#             echo "hi"
#             echo "hello"
#       - when:
#           condition:
#             or:
#               - equals: [circleci-project-setup, "<< pipeline.git.branch >>"]
#           steps:
#             - run:
#                 name: hey
#                 command: echo "hello"

jobs:
  # checking:
  #   steps:
  #     - test:
  #         command: echo "hi"
  you:
    steps:
      - run:
         name: hey
         command: echo "hello"
workflows:
  test-flow:
    jobs:
      - you
      - checking
