# .github/workflows/basic.yml

name: Echo Workflow - Parallel Jobs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from Test Job
        run: echo "✅ This is the Test Job - Running..."

      - name: Another echo
        run: echo "✅ Test Job Completed!"

  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from Build Job
        run: echo "🚀 This is the Build Job - Running in parallel..."

      - name: Another echo
        run: echo "🚀 Build Job Completed!"
