name: Test, Build, and Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.branch == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "Running tests..."
          echo "Tests passed!"
      - name: Print message
        run: echo "Test job completed!"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Building project..."
          echo "Build successful!"
      - name: Print message
        run: echo "Build job completed!"

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.event.branch == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploying project..."
          echo "Deployment successful!"
      - name: Print message
        run: echo "Deployment completed!"
