name: Python Script Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Script
        run: |
          python -c "import sys; print('Hello, World!'); print('Python Version:', sys.version)"
