name: Python Script Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Script
        shell: python
        run: |
          a = 2
          b = 1
          c = 2
          numbers = [a, b, c]
          if 1 in numbers:
            print('Error: Variable \'a\' or \'b\' is 1.')
            exit(1)
          else:
            exit(0)
