name: Simple CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  stage-one:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Print message
        run: |
          echo "This is Stage One - Running basic checks"
          echo b = ${{env.a}} >> $GITHUB_ENV
      - name: Printing the variables
        run: echo $b

