
name: Python Script Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Script
        shell: python
        env:
          a: 1
          b: 2
        run: |
          numbers = [${{ a }}, ${{ b }}]
          if 1 in numbers:
            print('Error: Variable \'a\' or \'b\' is 1.')
            exit(1)
          else:
            exit(0)
