name: Simple CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  stage-one:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Print message
        run: |
          echo "This is Stage One - Running basic checks"
          echo variable HI is = ${{ vars.HI }}
          echo secret is = ${{ secrets.SET }}
          echo "ab=${{ vars.HI }}" >> $GITHUB_ENV
          echo "${{ env.ab }}"
          echo "Printing ab: '${{ env.ab }}'"
          echo "Printi1ng ab: ${{ env.ab }}"
      - name: variable_printing
        run: |
          echo "${{ env.ab }}"
          echo "Printing ab: '${{ env.ab }}'"
          echo "Printi1ng ab: ${{ env.ab }}"
          echo Printi1ng ab: ${{ env.ab }}



