name: Echo Workflow - Parallel Jobs

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter paths (using dorny/paths-filter)
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            # Define filters for your paths
            frontend:
              - 'test/an/*'

      - name: Run Frontend tests
        if: steps.filter.outputs.frontend == 'true'  # Runs only if frontend files were changed
        run: |
          echo "Running frontend tests..."
          # Add your commands to run frontend tests

      
