name: Echo Workflow - Parallel Jobs

on:
  pull_request:
    branches:
      - main
jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - name: Filter paths (using dorny/paths-filter)
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            # Define filters for your paths
            frontend:
              - 'test/an/*'
      - name: Run my echo action
        uses: ./.github/actions/my-echo-action
        if: steps.filter.outputs.frontend == 'true'
        with:
          message: 'Hello from GitHub Actions!'
      

      - name: Run Frontend tests
        if: steps.filter.outputs.frontend == 'true'  # Runs only if frontend files were changed
        run: |
          echo "Running frontend tests..."
          # Add your commands to run frontend tests

      
