name: Python Script Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Script
        env:
          a: ${{ github.event.inputs.a }}
          b: ${{ github.event.inputs.b }}
        run: |
          python -c "
            import os
            import sys
            a = int(os.environ.get('a', 0))
            b = int(os.environ.get('b', 0))
            numbers = [a, b]
            if 1 in numbers:
              print('Error: Variable \'a\' or \'b\' is 1.')
              sys.exit(1)
            else:
              sys.exit(0)
          "
